const listamascotas = [
{"nombre":"Zoe","raza":"Ragdoll","color":"gris","fechanac":"31/10/2022"},
{"nombre":"Charlie","raza":"Bulldog","color":null,"fechanac":null},
{"nombre":"Lucy","raza":"Ragdoll","color":"blanco","fechanac":"28/03/2023"},
{"nombre":"Lucy","raza":"Poodle","color":"mezcla","fechanac":"17/06/2023"},
{"nombre":"Ruby","raza":"Ragdoll","color":null,"fechanac":"04/12/2022"},
{"nombre":"Bailey","raza":"Labrador Retriever","color":"marrón","fechanac":"20/11/2022"},
{"nombre":"Daisy","raza":null,"color":"gris","fechanac":"30/05/2023"},
{"nombre":"Oliver","raza":"Bulldog","color":null,"fechanac":"12/07/2023"},
{"nombre":"Cooper","raza":"Maine Coon","color":"blanco","fechanac":"29/09/2023"},
{"nombre":"Charlie","raza":"Persian","color":"negro","fechanac":"16/09/2023"},
{"nombre":"Zoe","raza":"Maine Coon","color":"mezcla","fechanac":"22/06/2023"},
{"nombre":"Bailey","raza":"Bulldog","color":"blanco","fechanac":"11/01/2023"},
{"nombre":"Cooper","raza":null,"color":"negro","fechanac":"08/11/2022"},
{"nombre":"Luna","raza":"Sphynx","color":"blanco","fechanac":null},
{"nombre":"Cooper","raza":"Siamese","color":"marrón","fechanac":"01/02/2023"},
{"nombre":"Molly","raza":"Poodle","color":"marrón","fechanac":"23/08/2023"},
{"nombre":"Coco","raza":"Labrador Retriever","color":"blanco","fechanac":null},
{"nombre":"Tucker","raza":"German Shepherd","color":"gris","fechanac":null},
{"nombre":"Coco","raza":"Siamese","color":"mezcla","fechanac":"03/12/2022"},
{"nombre":"Max","raza":"Maine Coon","color":"mezcla","fechanac":"27/08/2023"},
{"nombre":"Oliver","raza":"Ragdoll","color":null,"fechanac":"22/10/2023"},
{"nombre":"Rocky","raza":"Ragdoll","color":"negro","fechanac":"24/10/2022"},
{"nombre":"Molly","raza":"Persian","color":"gris","fechanac":"19/08/2023"},
{"nombre":"Lucy","raza":"Poodle","color":"marrón","fechanac":"01/06/2023"},
{"nombre":"Molly","raza":"Maine Coon","color":"negro","fechanac":"09/01/2023"},
{"nombre":"Rocky","raza":"Ragdoll","color":"mezcla","fechanac":"15/08/2023"},
{"nombre":"Max","raza":"Ragdoll","color":"blanco","fechanac":"07/10/2022"},
{"nombre":"Bear","raza":"Bulldog","color":"blanco","fechanac":"10/03/2023"},
{"nombre":"Milo","raza":"Siamese","color":"negro","fechanac":"07/10/2023"},
{"nombre":"Zoe","raza":"Sphynx","color":"marrón","fechanac":"06/08/2023"},
{"nombre":"Max","raza":null,"color":null,"fechanac":"27/04/2023"},
{"nombre":"Luna","raza":"Golden Retriever","color":"negro","fechanac":"25/04/2023"},
{"nombre":"Ruby","raza":"Poodle","color":"negro","fechanac":null},
{"nombre":"Rocky","raza":"Persian","color":"gris","fechanac":null},
{"nombre":"Sadie","raza":"Labrador Retriever","color":"blanco","fechanac":"26/06/2023"},
{"nombre":"Milo","raza":"Golden Retriever","color":"mezcla","fechanac":"09/09/2023"},
{"nombre":"Sadie","raza":"Siamese","color":"marrón","fechanac":null},
{"nombre":"Zoe","raza":"Golden Retriever","color":"blanco","fechanac":null},
{"nombre":"Tucker","raza":"Maine Coon","color":"gris","fechanac":"19/01/2023"},
{"nombre":"Zoe","raza":"Poodle","color":null,"fechanac":"16/06/2023"},
{"nombre":"Molly","raza":"Siamese","color":"marrón","fechanac":"27/07/2023"},
{"nombre":"Milo","raza":"Sphynx","color":"gris","fechanac":"12/01/2023"}
]
